### ISSUE TITLE
Error on Debian on first check_mode run

### ISSUE THREAD

**Issue by Al-thi** [geerlingguy/ansible-role-exim#10]
Hello,

This role fails on Debian when playing the following tasks in check_mode on a fresh server : 
```yaml
- name: Configure exim (Debian only).
  lineinfile:
    dest: "{{ exim_configuration_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^dc_eximconfig_configtype'
      line: "dc_eximconfig_configtype='{{ exim_dc_eximconfig_configtype }}'"
    - regexp: '^dc_localdelivery'
      line: "dc_localdelivery='{{ exim_dc_localdelivery }}'"
  notify: restart exim
  when: ansible_os_family == 'Debian'

- name: Configure primary_hostname (if set).
  lineinfile:
    dest: "{{ exim_configuration_file }}"
    regexp: '^#?\s?primary_hostname'
    line: "primary_hostname={{ exim_primary_hostname }}"
    state: present
  notify: restart exim
  when: exim_primary_hostname is defined and exim_primary_hostname

- name: Ensure exim is running.
  service: "name={{ exim_daemon }} state=started enabled=yes"
```

with the following error message : 
```
failed: [xxx] (item={'regexp': '^dc_eximconfig_configtype', 'line': "dc_eximconfig_configtype='internet'"}) => {"ansible_loop_var": "item", "changed": false, "item": {"line": "dc_eximconfig_configtype='internet'", "regexp": "^dc_eximconfig_configtype"}, "msg": "Destination /etc/exim4/update-exim4.conf.conf does not exist !", "rc": 257}
failed: [xxx] (item={'regexp': '^dc_localdelivery', 'line': "dc_localdelivery='mail_spool'"}) => {"ansible_loop_var": "item", "changed": false, "item": {"line": "dc_localdelivery='mail_spool'", "regexp": "^dc_localdelivery"}, "msg": "Destination /etc/exim4/update-exim4.conf.conf does not exist !", "rc": 257}
```
and : 
```
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Could not find the requested service exim4: host"}
```

because exim is not installed and therefore the destination file does not exist, just like the systemd service.

I suggest adding the following line to these tasks to ignore check_mode errors : 
```yaml
  ignore_errors: "{{ ansible_check_mode }}"
```
